spring.datasource.url=jdbc:mysql://localhost:3308/career_guidances
spring.datasource.username=root
spring.datasource.password=meghana

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true